### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by deolla** [deolla/boilerplate_nodeJs#6]
Authentication (including social authentication) + magic link authentication + in-app authentication screens (e.g change password)

**Comment by deolla** [comment]
Review this too

**Comment by coderoyalty** [comment]
My Review:

- all authentication uses the POST method
- all authentication-based endpoints belongs to the base URL `/auth`
- support password-based authentication with 200 status code for `/login`
- support for OAuth/Social based authentication: Google and Facebook
- support for magic-link authentication: provide endpoint to request a link, and another for verifying the link

**Comment by deolla** [comment]
Do I have an error there?? And what are the changes you think I need to make??

**Comment by coderoyalty** [comment]
You're good to go.

**Comment by deolla** [comment]
Alright
